// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx4nktN8dIXZlnV4-iiA7vFFBaYiJDnj4',
    appId: '1:193721869714:web:a531735f5bbd63d6a48d4b',
    messagingSenderId: '193721869714',
    projectId: 'warranty-valut',
    authDomain: 'warranty-valut.firebaseapp.com',
    storageBucket: 'warranty-valut.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2-qDhvMVVqYGasb_aJ8vjvkEPQ_nVfS8',
    appId: '1:193721869714:android:6ed1ec214f028262a48d4b',
    messagingSenderId: '193721869714',
    projectId: 'warranty-valut',
    storageBucket: 'warranty-valut.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGXRE6PwaEHa0cfOpZFGZ77Z_Vf8YPupo',
    appId: '1:193721869714:ios:ce1be8067d89dc99a48d4b',
    messagingSenderId: '193721869714',
    projectId: 'warranty-valut',
    storageBucket: 'warranty-valut.firebasestorage.app',
    iosBundleId: 'com.miniproject.expensetracker.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGXRE6PwaEHa0cfOpZFGZ77Z_Vf8YPupo',
    appId: '1:193721869714:ios:ce1be8067d89dc99a48d4b',
    messagingSenderId: '193721869714',
    projectId: 'warranty-valut',
    storageBucket: 'warranty-valut.firebasestorage.app',
    iosBundleId: 'com.miniproject.expensetracker.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx4nktN8dIXZlnV4-iiA7vFFBaYiJDnj4',
    appId: '1:193721869714:web:03381c09283520f8a48d4b',
    messagingSenderId: '193721869714',
    projectId: 'warranty-valut',
    authDomain: 'warranty-valut.firebaseapp.com',
    storageBucket: 'warranty-valut.firebasestorage.app',
  );
}
